### PR TITLE
Update global.css to improve typography on smaller resolutions

### PR DESCRIPTION
**Pull request by fbracht**
I have no idea what I'm doing, but it works on Inspector. :D

### CODE REVIEW

**Review by filipekiss — CHANGES_REQUESTED** [review]
Hey @fbracht, thank you for taking the time to contribute! I'm using [tailwind](https://tailwindcss.com/) as my CSS framework and I'd like to keep custom CSS to a minimum. Instead of writing the rule here, maybe add the proper class to the [body tag](https://github.com/filipekiss/blog/blob/b7bc99696b65482d9ed9ab14333264222630922a/src/components/Meta/Meta.tsx#L80)?

Here are some links to help you with that:

 - [tailwind font-size documentation](https://tailwindcss.com/docs/font-size/#app)
 - [tailwind font-size documentation - responsive examples](https://tailwindcss.com/docs/font-size/#responsive)

Let me know if you have any doubts. :)

**Comment by filipekiss** [comment]
Hey @fbracht, you still looking into this? :)

**Comment by fbracht** [comment]
Hey @filipekiss. To be honest, I think I’m dropping this for now. Learning the workings of a new CSS framework just for a small typography tweak sounds a bit overwhelming for me at the moment. I certainly should have said so when you first replied, and I apologize for ghosting you. :)

Cheers, and thank you for the feedback! Someday, hopefully, I’ll be a good open source contributor. :)

**Comment by filipekiss** [comment]
No worries, mate :)

**Comment by filipekiss** [comment]
Hey @fbracht, just so you know: I've applied your patch after I made a few other changes :) Thanks for the help!

**Pull request closed without merging**
